### ISSUE TITLE
Overlay mode crash in Android 14

### ISSUE THREAD

**Issue by memostark** [memostark/Speakable#228]
This is due to a new change when targeting SDK 34, a callback needs to be registered before creating a `VirtualDisplay`.

See [docs](https://developer.android.com/about/versions/14/behavior-changes-14#callback).

**Comment by Hamad854** [comment]
How to fix ?
Can You update

**Comment by memostark** [comment]
@Hamad854 Just released an update with a fix, unfortunately, it is now more limited due to restrictions introduced with Android 14
https://github.com/memostark/Speakable/releases/tag/v.1.16.1
